// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB9xWmDIFCf76yx80nvfe5Fn59Q0yr2rk',
    appId: '1:576836903168:web:a241811069c2e25af353e5',
    messagingSenderId: '576836903168',
    projectId: 'appgiaohangonline',
    authDomain: 'appgiaohangonline.firebaseapp.com',
    storageBucket: 'appgiaohangonline.firebasestorage.app',
    measurementId: 'G-ERHPT6J4RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTozx8by6wdVjyYPvS3YuTuwtMkZTkqk4',
    appId: '1:576836903168:android:c97a65f048ab1cf2f353e5',
    messagingSenderId: '576836903168',
    projectId: 'appgiaohangonline',
    storageBucket: 'appgiaohangonline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESIpNTb_abIvWs7vJiNC-uyDoCe5p0Iw',
    appId: '1:576836903168:ios:70a25ad556d5a13df353e5',
    messagingSenderId: '576836903168',
    projectId: 'appgiaohangonline',
    storageBucket: 'appgiaohangonline.firebasestorage.app',
    iosBundleId: 'com.example.appgiaohang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESIpNTb_abIvWs7vJiNC-uyDoCe5p0Iw',
    appId: '1:576836903168:ios:70a25ad556d5a13df353e5',
    messagingSenderId: '576836903168',
    projectId: 'appgiaohangonline',
    storageBucket: 'appgiaohangonline.firebasestorage.app',
    iosBundleId: 'com.example.appgiaohang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB9xWmDIFCf76yx80nvfe5Fn59Q0yr2rk',
    appId: '1:576836903168:web:190bcb9e86d1b6d7f353e5',
    messagingSenderId: '576836903168',
    projectId: 'appgiaohangonline',
    authDomain: 'appgiaohangonline.firebaseapp.com',
    storageBucket: 'appgiaohangonline.firebasestorage.app',
    measurementId: 'G-1DJLXXW3VR',
  );

}